
extalion_sentry_configuration:
  path: extsentry/configuration
  methods: [GET,POST]
  defaults:
    _controller: Extalion\Sentry\Controller\Admin\ConfigurationController::indexAction
    _legacy_controller: ExtSentryAdminConfigurationController
