
services:
  _defaults:
    public: true

  extalion.sentry.repository.configuration:
    class: Extalion\Sentry\Repository\Configuration
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Extalion\Sentry\Entity\ExtsentryConfiguration
